# Generated by Django 5.0.14 on 2026-07-25 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0012_remove_default_side_menu_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='EbookDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('review_required', 'Review required'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=24)),
                ('toc_start_page', models.PositiveIntegerField(blank=True, null=True)),
                ('toc_end_page', models.PositiveIntegerField(blank=True, null=True)),
                ('total_pdf_pages', models.PositiveIntegerField(blank=True, null=True)),
                ('page_number_offset', models.IntegerField(default=0)),
                ('processing_error', models.TextField(blank=True)),
                ('processing_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ebook_document', to='library.book')),
            ],
            options={
                'ordering': ('book__title', 'id'),
            },
        ),
        migrations.CreateModel(
            name='EbookLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('start_page', models.PositiveIntegerField()),
                ('end_page', models.PositiveIntegerField(blank=True, null=True)),
                ('source_toc_page', models.PositiveIntegerField(blank=True, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('raw_ocr_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='ebook_reader.ebookdocument')),
            ],
            options={
                'ordering': ('ebook', 'order', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='ebookdocument',
            index=models.Index(fields=['status'], name='ebook_doc_status_idx'),
        ),
        migrations.AddIndex(
            model_name='ebookdocument',
            index=models.Index(fields=['book', 'status'], name='ebook_doc_book_status_idx'),
        ),
        migrations.AddIndex(
            model_name='ebookdocument',
            index=models.Index(fields=['updated_at'], name='ebook_doc_updated_idx'),
        ),
        migrations.AddConstraint(
            model_name='ebookdocument',
            constraint=models.CheckConstraint(check=models.Q(('toc_end_page__isnull', True), models.Q(('toc_end_page__gte', models.F('toc_start_page')), ('toc_start_page__isnull', False)), _connector='OR'), name='ebook_doc_toc_end_gte_start'),
        ),
        migrations.AddIndex(
            model_name='ebooklesson',
            index=models.Index(fields=['ebook', 'order'], name='ebook_lesson_order_idx'),
        ),
        migrations.AddIndex(
            model_name='ebooklesson',
            index=models.Index(fields=['ebook', 'start_page'], name='ebook_lesson_start_idx'),
        ),
        migrations.AddIndex(
            model_name='ebooklesson',
            index=models.Index(fields=['ebook', 'is_verified'], name='ebook_lesson_verified_idx'),
        ),
        migrations.AddConstraint(
            model_name='ebooklesson',
            constraint=models.UniqueConstraint(fields=('ebook', 'order'), name='unique_lesson_order_per_ebook'),
        ),
        migrations.AddConstraint(
            model_name='ebooklesson',
            constraint=models.CheckConstraint(check=models.Q(('start_page__gte', 1)), name='ebook_lesson_start_page_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='ebooklesson',
            constraint=models.CheckConstraint(check=models.Q(('end_page__isnull', True), ('end_page__gte', models.F('start_page')), _connector='OR'), name='ebook_lesson_end_page_gte_start'),
        ),
    ]
