# Generated by Django 5.0.14 on 2026-07-25 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebook_reader', '0001_initial'),
        ('library', '0012_remove_default_side_menu_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebookdocument',
            name='detected_toc_end_page',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ebookdocument',
            name='detected_toc_start_page',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ebookdocument',
            name='toc_detection_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ebookdocument',
            name='toc_detection_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='ebookdocument',
            name='toc_mode',
            field=models.CharField(choices=[('auto', 'Auto detect'), ('manual', 'Manual page range'), ('none', 'No TOC')], default='auto', max_length=12),
        ),
        migrations.AddField(
            model_name='ebookdocument',
            name='toc_scan_page_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='ebookdocument',
            index=models.Index(fields=['toc_mode'], name='ebook_doc_toc_mode_idx'),
        ),
        migrations.AddConstraint(
            model_name='ebookdocument',
            constraint=models.CheckConstraint(check=models.Q(('detected_toc_end_page__isnull', True), models.Q(('detected_toc_end_page__gte', models.F('detected_toc_start_page')), ('detected_toc_start_page__isnull', False)), _connector='OR'), name='ebook_doc_detected_toc_end_gte_start'),
        ),
    ]
