# Generated by Django 5.0.14 on 2026-07-25 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebook_reader', '0002_ebookdocument_detected_toc_end_page_and_more'),
        ('library', '0012_remove_default_side_menu_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='EbookPageMappingAnchor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printed_page_number', models.PositiveIntegerField()),
                ('physical_pdf_page', models.PositiveIntegerField()),
                ('note', models.CharField(blank=True, max_length=255)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('ebook', 'printed_page_number', 'physical_pdf_page', 'id'),
            },
        ),
        migrations.AddField(
            model_name='ebookdocument',
            name='detected_page_number_offset',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ebookdocument',
            name='page_mapping_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ebookdocument',
            name='page_mapping_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='ebookdocument',
            name='page_mapping_mode',
            field=models.CharField(choices=[('auto', 'Auto'), ('manual_offset', 'Manual offset'), ('manual_anchors', 'Manual anchors'), ('none', 'No printed page mapping')], default='auto', max_length=20),
        ),
        migrations.AddField(
            model_name='ebookdocument',
            name='page_mapping_status',
            field=models.CharField(choices=[('not_checked', 'Not checked'), ('detected', 'Detected'), ('review_required', 'Review required'), ('accepted', 'Accepted'), ('failed', 'Failed')], default='not_checked', max_length=20),
        ),
        migrations.AlterField(
            model_name='ebookdocument',
            name='page_number_offset',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='ebookdocument',
            index=models.Index(fields=['page_mapping_status'], name='ebook_doc_map_status_idx'),
        ),
        migrations.AddIndex(
            model_name='ebookdocument',
            index=models.Index(fields=['page_mapping_mode'], name='ebook_doc_map_mode_idx'),
        ),
        migrations.AddField(
            model_name='ebookpagemappinganchor',
            name='ebook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_mapping_anchors', to='ebook_reader.ebookdocument'),
        ),
        migrations.AddIndex(
            model_name='ebookpagemappinganchor',
            index=models.Index(fields=['ebook', 'printed_page_number'], name='ebook_map_anchor_print_idx'),
        ),
        migrations.AddIndex(
            model_name='ebookpagemappinganchor',
            index=models.Index(fields=['ebook', 'physical_pdf_page'], name='ebook_map_anchor_phys_idx'),
        ),
        migrations.AddConstraint(
            model_name='ebookpagemappinganchor',
            constraint=models.UniqueConstraint(fields=('ebook', 'printed_page_number', 'physical_pdf_page'), name='unique_page_mapping_anchor'),
        ),
        migrations.AddConstraint(
            model_name='ebookpagemappinganchor',
            constraint=models.CheckConstraint(check=models.Q(('printed_page_number__gte', 1)), name='ebook_map_anchor_print_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='ebookpagemappinganchor',
            constraint=models.CheckConstraint(check=models.Q(('physical_pdf_page__gte', 1)), name='ebook_map_anchor_phys_gte_1'),
        ),
    ]
