# Generated by Django 5.0.14 on 2026-07-25 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebook_reader', '0003_ebookpagemappinganchor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EbookProcessingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('skipped', 'Skipped'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('extraction_engine', models.CharField(blank=True, max_length=120)),
                ('parser_version', models.CharField(blank=True, max_length=40)),
                ('mapping_strategy', models.CharField(blank=True, max_length=120)),
                ('valid_count', models.PositiveIntegerField(default=0)),
                ('invalid_count', models.PositiveIntegerField(default=0)),
                ('unclassified_count', models.PositiveIntegerField(default=0)),
                ('diagnostics', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('-started_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='EbookTocCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_type', models.CharField(choices=[('invalid', 'Invalid'), ('unclassified', 'Unclassified')], max_length=20)),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('printed_page_number', models.PositiveIntegerField(blank=True, null=True)),
                ('proposed_pdf_page', models.PositiveIntegerField(blank=True, null=True)),
                ('source_toc_page', models.PositiveIntegerField(blank=True, null=True)),
                ('parser_strategy', models.CharField(blank=True, max_length=120)),
                ('raw_source_text', models.TextField(blank=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('diagnostics', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('ebook_document', 'source_toc_page', 'id'),
            },
        ),
        migrations.RemoveConstraint(
            model_name='ebooklesson',
            name='ebook_lesson_start_page_gte_1',
        ),
        migrations.RemoveConstraint(
            model_name='ebooklesson',
            name='ebook_lesson_end_page_gte_start',
        ),
        migrations.AddField(
            model_name='ebooklesson',
            name='is_manually_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ebooklesson',
            name='parser_strategy',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='ebooklesson',
            name='printed_page_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ebooklesson',
            name='warnings',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='ebooklesson',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ebooklesson',
            name='start_page',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ebookprocessingrun',
            name='ebook_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_runs', to='ebook_reader.ebookdocument'),
        ),
        migrations.AddField(
            model_name='ebooklesson',
            name='processing_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='ebook_reader.ebookprocessingrun'),
        ),
        migrations.AddConstraint(
            model_name='ebooklesson',
            constraint=models.CheckConstraint(check=models.Q(('start_page__isnull', True), ('start_page__gte', 1), _connector='OR'), name='ebook_lesson_start_page_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='ebooklesson',
            constraint=models.CheckConstraint(check=models.Q(('end_page__isnull', True), models.Q(('end_page__gte', models.F('start_page')), ('start_page__isnull', False)), _connector='OR'), name='ebook_lesson_end_page_gte_start'),
        ),
        migrations.AddField(
            model_name='ebooktoccandidate',
            name='ebook_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toc_candidates', to='ebook_reader.ebookdocument'),
        ),
        migrations.AddField(
            model_name='ebooktoccandidate',
            name='processing_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toc_candidates', to='ebook_reader.ebookprocessingrun'),
        ),
        migrations.AddIndex(
            model_name='ebookprocessingrun',
            index=models.Index(fields=['ebook_document', 'status'], name='ebook_run_doc_status_idx'),
        ),
        migrations.AddIndex(
            model_name='ebookprocessingrun',
            index=models.Index(fields=['started_at'], name='ebook_run_started_idx'),
        ),
        migrations.AddIndex(
            model_name='ebooktoccandidate',
            index=models.Index(fields=['ebook_document', 'candidate_type'], name='ebook_toc_cand_type_idx'),
        ),
        migrations.AddIndex(
            model_name='ebooktoccandidate',
            index=models.Index(fields=['processing_run', 'candidate_type'], name='ebook_toc_cand_run_idx'),
        ),
    ]
