# Generated by Django 5.0.14 on 2026-07-25 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebook_reader', '0005_ebooklesson_verified_at_ebooklesson_verified_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EbookReadingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_page', models.PositiveIntegerField()),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('last_read_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reading_progress', to='ebook_reader.ebooklesson')),
                ('ebook_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_progress', to='ebook_reader.ebookdocument')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ebook_reading_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-last_read_at', '-id'),
                'indexes': [models.Index(fields=['user', 'ebook_document'], name='ebook_progress_user_doc_idx'), models.Index(fields=['last_read_at'], name='ebook_progress_last_read_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='ebookreadingprogress',
            constraint=models.UniqueConstraint(fields=('user', 'ebook_document'), name='unique_ebook_progress_per_user'),
        ),
        migrations.AddConstraint(
            model_name='ebookreadingprogress',
            constraint=models.CheckConstraint(check=models.Q(('current_page__gte', 1)), name='ebook_progress_current_page_gte_1'),
        ),
    ]
