# Generated by Django 5.0.14 on 2026-07-25 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebook_reader', '0006_ebookreadingprogress_and_more'),
        ('library', '0012_remove_default_side_menu_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebookdocument',
            name='new_ebook_reader_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ebookdocument',
            name='new_ebook_reader_mobile_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ebookdocument',
            name='new_ebook_reader_web_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='ebookdocument',
            index=models.Index(fields=['status', 'new_ebook_reader_enabled'], name='ebook_doc_enabled_idx'),
        ),
    ]
