# Generated by Django 5.0.14 on 2026-08-01 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebook_reader', '0008_book_bookpage_indexitem_highlight'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='processed_pages',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='processing_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='book',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='book',
            name='total_pages',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookpage',
            name='extraction_method',
            field=models.CharField(choices=[('embedded', 'Embedded Unicode text'), ('legacy_converter', 'Legacy font converter'), ('ocr', 'Tesseract OCR'), ('fallback', 'Unconverted fallback')], default='embedded', max_length=24),
        ),
        migrations.AddField(
            model_name='bookpage',
            name='line_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookpage',
            name='plain_text',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='BookLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='ebook_reader.bookpage')),
            ],
            options={
                'ordering': ('page__page_number', 'line_number'),
                'indexes': [models.Index(fields=['page', 'line_number'], name='ebook_line_page_number_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='bookline',
            constraint=models.UniqueConstraint(fields=('page', 'line_number'), name='ebook_reader_unique_page_line'),
        ),
    ]
