# Generated by Django 5.0.14 on 2026-08-01 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebook_reader', '0009_scalable_line_ingestion'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['processing_status'], name='ebook_book_status_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['uploaded_at'], name='ebook_book_uploaded_idx'),
        ),
        migrations.AddIndex(
            model_name='bookpage',
            index=models.Index(fields=['book', 'extraction_method'], name='ebook_page_book_method_idx'),
        ),
    ]
