# Generated by Django 5.0.14 on 2026-08-01 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebook_reader', '0010_ingestion_indexes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookLine',
        ),
    ]
