# Generated by Django 5.0.14 on 2026-09-07 04:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebook_reader', '0011_remove_bookline'),
        ('library', '0015_chapter_page_range'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentEdition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_pdf', models.FileField(upload_to='content_sources/%Y/%m/')),
                ('source_sha256', models.CharField(max_length=64)),
                ('engine_version', models.CharField(default='structured-1', max_length=40)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('review', 'Needs review'), ('published', 'Published'), ('archived', 'Archived'), ('failed', 'Failed')], default='queued', max_length=16)),
                ('total_pages', models.PositiveIntegerField(default=0)),
                ('processed_pages', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_editions', to='library.book')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='ContentPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField()),
                ('layout', models.JSONField(default=dict)),
                ('plain_text', models.TextField(blank=True)),
                ('extraction_method', models.CharField(max_length=32)),
                ('issues', models.JSONField(blank=True, default=list)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='ebook_reader.contentedition')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('page_number',),
            },
        ),
        migrations.AddIndex(
            model_name='contentedition',
            index=models.Index(fields=['book', 'status'], name='content_book_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='contentpage',
            constraint=models.UniqueConstraint(fields=('edition', 'page_number'), name='content_edition_page_unique'),
        ),
    ]
