# Generated by Django 5.0.14 on 2026-09-07 05:14

import ebook_reader.content_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebook_reader', '0012_contentedition_contentpage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentedition',
            name='source_pdf',
            field=models.FileField(storage=ebook_reader.content_storage.ContentSourceStorage(), upload_to='content_sources/%Y/%m/'),
        ),
    ]
